@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":ExportCommand" as ExportCommand LOGIC_COLOR
end box

box Commons COMMONS_COLOR_T1
participant "<<class>>\nCsvUtil" as CsvUtil COMMONS_COLOR
end box

mainframe **sd** JSON file handling and CSV conversion <U+0020>

ExportCommand -> ExportCommand : readJsonFile()
activate ExportCommand

ExportCommand --> ExportCommand
deactivate ExportCommand

ExportCommand -> ExportCommand : readPersonsArray()
activate ExportCommand

ExportCommand --> ExportCommand
deactivate ExportCommand

ExportCommand -> ExportCommand : readExamsArray()
activate ExportCommand

ExportCommand --> ExportCommand
deactivate ExportCommand

ExportCommand -> ExportCommand : createCsvDirectory()
activate ExportCommand

ExportCommand --> ExportCommand
deactivate ExportCommand

ExportCommand -> CsvUtil : writeToCsvFile()
activate CsvUtil

CsvUtil -> CsvUtil : buildCsvSchema()
activate CsvUtil

CsvUtil --> CsvUtil
deactivate CsvUtil

CsvUtil --> ExportCommand
deactivate CsvUtil

@enduml
