@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes find command;

if () then ([command is in invalid format])
    :Show invalid command format as error message;


else ([else])
    : Displays the students that match the search criteria;
endif
stop


@enduml
