@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:Filepath input is parsed;
if () is ([file is a .csv file]) then
  :importExamScores command is executed with the filepath;
  if () is ([no exception is thrown]) then
  :Read the rows of the CSV file;
      if () is ([email header exists only in the first column]) then
        :Start adding scores;
      else ([else])
        :Reject;
      endif
  else ([else])
    :Reject;
  endif
else ([else])
  :Reject;
endif
stop


@enduml
