›@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant "i:ImportCommand" as ImportCommand LOGIC_COLOR
participant "<<class>>\nCsvUtil" as CsvUtil LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
participant "a:AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "p:Person" as Person MODEL_COLOR
participant "m:Model" as Model MODEL_COLOR
end box

 -> ImportCommand : execute(m)
activate ImportCommand

ImportCommand -> CsvUtil : readCsvfile()
activate CsvUtil
CsvUtil --> ImportCommand : personsData
deactivate CsvUtil

ImportCommand -> ImportCommand : addToModel(personsData)
activate ImportCommand

loop personData in personsData

ImportCommand -> ImportCommand : convertToAddCommandInput(personData)
activate ImportCommand
ImportCommand --> ImportCommand : addCommandInput
deactivate ImportCommand

ImportCommand -> AddCommandParser : parse(addCommandInput)
activate AddCommandParser
create AddCommand
AddCommandParser -> AddCommand : new AddCommand()
activate AddCommand
AddCommand --> AddCommandParser
deactivate AddCommand
AddCommandParser --> ImportCommand
deactivate AddCommandParser

ImportCommand -> AddCommand
activate AddCommand
ref over AddCommand, Person, Model : Add Command Execution
AddCommand --> ImportCommand
deactivate AddCommand
destroy AddCommand
end
ImportCommand --> ImportCommand
deactivate ImportCommand

create CommandResult
ImportCommand -> CommandResult
activate CommandResult

CommandResult --> ImportCommand: CommandResult
deactivate CommandResult

 <--  ImportCommand : CommandResult
deactivate ImportCommand

@enduml
